# Generated by Django 4.1.4 on 2022-12-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart_or_sold_qunatity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
