# Generated by Django 4.1.4 on 2022-12-12 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_cart_or_sold_qunatity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cart_or_sold_qunatity",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
